### ISSUE TITLE
How to set a delegated event on a given element and not globally?

### ISSUE THREAD

**Issue by meglio** [dgraham/delegated-events#15]
In jQuery, I can set a delegated event handler to a specific element in the DOM tree:

```js
$element.on('click', '.selector', callbackFunc)
```
How do I do the same with delegated-events? 

In the source code I see this:

```js
function on(name, selector, fn) {
  // ...
  document.addEventListener(name, dispatch, capture);
  // ..
  }
```

Does it mean event listeners are always/only attached to the document?

**Comment by dgraham** [comment]
> Does it mean event listeners are always/only attached to the document?

Yes, listeners are attached only to `document`.
