### ISSUE TITLE
Attaching events to child iframes

### ISSUE THREAD

**Issue by elronalds** [dgraham/delegated-events#16]
I'd like to be able to attach events within a child iframe from the parent document js code?   This doesn't seem possible in the current implementation.   Thoughts?

**Comment by dgraham** [comment]
Events do not bubble across document boundaries, so you would need to delegate up to the iframe's document and send some of the event across a [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) call to the other document.
