### ISSUE TITLE
How to use in browser?

### ISSUE THREAD

**Issue by limonte** [dgraham/delegated-events#17]
Is there a possibility to use `delegated-events` in an old-school way? Something like this:

```html
<script src="/path/to/delegated-events.js"></script>
```

```js
window.on(...)
window.off(...)
window.fire(...)
```

**Comment by dgraham** [comment]
The package's `main` file entry points to `dist/index.umd.js`. If you copy that file out of the package, or clone the repository and run `npm run build`, you can reference it with a script tag.

The functions are exported on a `delegated-events` global.

```js
window['delegated-events'].on(…)
```
