### ISSUE TITLE
Getting access to the fired event object

### ISSUE THREAD

**Issue by stof** [dgraham/delegated-events#21]
The `fire` utility triggers a cancellable CustomEvent. But as it does not return the event object, there is no way to know whether the event was cancelled or no.

**Comment by dgraham** [comment]
It [returns](https://github.com/dgraham/delegated-events/blob/23bb4bac02225a34888e87c43eb0853fd5412def/delegated-events.js#L120) the result of [`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent), which is `false` if the event was cancelled by a listener.

**Comment by stof** [comment]
then the flow types are wrong, as it says it returns `void`
