### ISSUE TITLE
Form submit event

### ISSUE THREAD

**Issue by ray73864** [dgraham/delegated-events#25]
Is there any way to get this to work with a form submit?

I thought it might be a simple matter of using the custom event side of things, but even after trying that my form wasn't submitting.

I am doing the following:

```
window['delegate-events'].on('form:submit', document.querySelector('#myForm'), function(e) { e.preventDefault(); console.log('Form submitted!') });
```
If I then go to the developer tools console and do
```
window['delegate-events'].fire(document.querySelector('#myForm'), 'form:submit', {});
```
It returns 'true', but the actual event never triggers ('Form submitted' doesn't appear in the console).

**Comment by ray73864** [comment]
Looking at it further, If I set a breakpoint at the end of the 'fire' code in the delegate-events JS file and then trigger the event, it does actually go into it, but the '.on()' event itself (I have a breakpoint inside of it) never gets called.

**Comment by dgraham** [comment]
You might be seeing this form submission behavior.

>The submit event only fires when the user clicks a submit button in a form. The event is not raised when calling the form.submit() method directly.
— https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event

You can dispatch a custom event before calling submit via script.

```js
function requestSubmit(form) {
  if (fire(form, 'submit', true)) {
    form.submit()
  }
}
```
