### ISSUE TITLE
On does not intercept fire events

### ISSUE THREAD

**Issue by dy** [dgraham/delegated-events#28]
```js
on('body', 'init', e => {
  console.log(e)
})
fire(document.body, 'init')
```
`console.log` is never triggered.

[delegate-it](https://github.com/delegate-it) works fine:
```js
import on from 'delegate-it'
import { fire } from 'delegated-events'

on('body', 'init', e => console.log(e))
fire(document.body, 'init')
```

**Comment by dgraham** [comment]
The [first argument](https://github.com/dgraham/delegated-events/blob/177207091ed9f1a41e67df1b2e8423a0ad794706/delegated-events.js#L93) to `on` is the event name and the second argument is the selector.

**Comment by dy** [comment]
🤦‍♂ shame on me
