### ISSUE TITLE
Generic constraint instead of any on the fire function

### ISSUE THREAD

**Issue by xt0rted** [dgraham/delegated-events#34]
On the `fire` function the last parameter is `any`, if that was changed to a generic you could optionally use an interface to help with type checking and the behavior should remain the same as `any`. Maybe there's side effects I'm not realizing, but if there aren't any is there any objection to changing the definition to something like this?

```typescript
export function fire<T>(target: Document | Element, name: string, detail?: T): boolean;
```

Example usage:

```typescript
interface ISomeEvent {
  val1: int;
  val2: string;
}

// adds type checking to the event details
fire<ISomeEvent>(target, "do:something", {
  val1: 0,
  val2: "",
});

// remains the same as `any`
fire(target, "do:something", {
  val1: 0,
  val2: "",
});
```

**Comment by koddsson** [comment]
What would you gain from having the function be a generic? If I'm reading this correctly then you could achieve the same by doing the type assertion before passing the variable to `fire(..)`?

```ts
function fire(target: Element, eventName: string, detail: any) { }
const target = new HTMLElement()

interface ISomeEvent {
  val1: number;
  val2: string;
}

// No error
const correctEvent: ISomeEvent = {
  val1: 0,
  val2: "",
}

// Error!
const wrongEvent: ISomeEvent = {
  foo: "bar"
}

fire(target, "do:something", correctEvent);
fire(target, "do:something", wrongEvent);
```

I guess the way I look at it, `delegated-events` doesn't care what you pass it as a third argument and the type function signature reflects that. The app using `delegated-events` cares about the type so it should handle the type checking.

**Comment by xt0rted** [comment]
The generic parameter simplifies the code a bit I think, and since the object passed to `fire` is the same that's used in `on` (which can have a generic parameter with `CustomEvent<T>`) there's consistency between them along with the extra type checking.

For now I added a `delegated-events.d.ts` to my project with with an override.

```typescript
declare module "delegated-events" {
  export function fire<T = any>(target: Element, name: string, detail?: T): boolean;
}
```

**Comment by keithamus** [comment]
@xt0rted local to an individual project, I like to maintain a .d.ts file something like this, keeping a list of the projects well-known custom event names in the `CustomEventMap`:

```typescript
// events.d.ts

interface CustomEventMap {
  'my-event:foo': {
    something: boolean
  }
}
type CustomDelegatedEventListener<T> = (this: Element, ev: CustomEvent<T> & {currentTarget: Element}) => any

declare module 'delegated-events' {
  export function fire<K extends keyof CustomEventMap>(target: Element, name: K, detail: CustomEventMap[K]): boolean
  export function on<K extends keyof CustomEventMap>(
    name: K,
    selector: string,
    listener: CustomDelegatedEventListener<CustomEventMap[K]>
  ): boolean
}

declare global {
  interface Document {
    addEventListener<K extends keyof CustomEventMap>(
      type: K,
      listener: (this: Document, ev: CustomEvent<CustomEventMap[K]>) => unknown,
      options?: boolean | AddEventListenerOptions
    ): void
  }
  interface HTMLElement {
    addEventListener<K extends keyof CustomEventMap>(
      type: K,
      listener: (this: Document, ev: CustomEvent<CustomEventMap[K]>) => unknown,
      options?: boolean | AddEventListenerOptions
    ): void
  }
}
```

This allows for the following with full TS support:

```typescript
fire(document.body, 'my-event:foo', {something: true})
on('my-event:foo', 'body', event => {
  event.detail.something // typescript knows this is a boolean
})
document.addEventListener('my-event:foo', event => {
  event.detail.something
})
document.body.addEventListener('my-event:foo', event => {
  event.detail.something
})
```

This also gives my editor full autocomplete & type tooltip capabilities:

![image](https://user-images.githubusercontent.com/118266/87772002-09a88c80-c819-11ea-86bc-b67a617b7d7a.png)

You can do this with the currently released version of `delegated-events`, it works real nice - but there's not much we could add to `delegated-events` to make this process easier.

**Comment by xt0rted** [comment]
Thanks for that @keithamus. I had come up with something similar for the `on` function but your example is a lot nicer.
